# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ms-lipidomics"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John T. Prince"]
  s.date = "2012-02-24"
  s.description = "does ms lipidomics"
  s.email = "jtprince@gmail.com"
  s.executables = ["lipidomic-search.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/lipidomic-search.rb",
    "lib/ms/lipid.rb",
    "lib/ms/lipid/ion.rb",
    "lib/ms/lipid/modification.rb",
    "lib/ms/lipid/search.rb",
    "lib/ms/lipid/search/bin.rb",
    "lib/ms/lipid/search/db_isobar_group.rb",
    "lib/ms/lipid/search/hit.rb",
    "lib/ms/lipid/search/probability_distribution.rb",
    "lib/ms/lipid/search/query.rb",
    "lib/ms/lipid_maps.rb",
    "spec/ms/lipid/ion_spec.rb",
    "spec/ms/lipid/modification_spec.rb",
    "spec/ms/lipid/search_spec.rb",
    "spec/ms/lipid_maps_spec.rb",
    "spec/ms/lipid_spec.rb",
    "spec/spec_helper.rb",
    "spec/testfiles/lipidmaps_short.tsv"
  ]
  s.homepage = "http://github.com/princelab/ms-lipidomics"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "mass spectrometry based lipidomics - especially shotgun lipidomics"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mspire>, [">= 0.6.19"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<mspire>, [">= 0.6.19"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mspire>, [">= 0.6.19"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

